host01:
    cpus: 16
    numa_nodes: 
      - id: 0
        cpus: 0-7
      - id: 1
        cpus: 8-15
    isolated_cpus: 2-15
    shared_cpus: 0,1  # for logging and admin
    nics:
      - name: eth0
        ip: 192.168.1.100
        type: ethernet
      - name: sf0
        ip: 192.168.1.101
        type: solarflare
